config/routes.rb
Rails.application.routes.draw do

  resources :manager_notes
  devise_for :partners
  devise_scope :partners do
    get  'partners/admin_new' => 'partners#admin_new'
    post 'partners/admin_create' => 'partners#admin_create'
  end

  resource :mains, only: :index
  get 'practice_survey_thanks', to: 'mains#practice_survey_thanks'
  get 'admin_area', to: 'mains#admin_area'
  get 'supervisor_area', to: 'mains#supervisor_area'
  get 'practice_contacts', to: 'mains#practice_contacts'
  get 'practice_progress', to: 'mains#practice_progress'
  get 'survey_progress', to: 'mains#survey_progress'
  get 'practice_lifetime/:id', to: 'mains#practice_lifetime', as: 'practice_lifetime'
  get 'qualitative_export', to: 'ivcontacts#qualitative_export'

  resources :surveys do
    collection do
      post :import
      get :import_results
    end
  end
  get 'practice_survey_practices', to: 'surveys#practice_survey_practices'
  get 'staff_survey_practices', to: 'surveys#staff_survey_practices'

  resources :sites do
    resources :partners
  end
  resources :partners do
    resources :events
    resources :practices
    get 'list', on: :collection
    get 'assign_practice', on: :member
  end
  resources :practices do
    resources :events
    resources :personnels
    get 'export', on: :collection
  end
  resources :coach_practices do
    resources :ivcontacts
    resources :coach_items
    get 'list', on: :member
  end
  resources :ivcontacts do
    resources :high_leverage_change_tests
  end
  resources :coach_assignments, only: [ :index, :edit, :update ]
  resources :events
  resources :personnels
  resources :practice_surveys
  resources :high_leverage_change_tests
  resources :coach_items
  resources :dropouts, only: [ :index, :edit, :update ]

  root 'mains#index'
  as :partner do
    get 'partners', :to => 'partners#show', :as => :partner_root
  end

end

app/controllers/coach_practices_controller.rb
class CoachPracticesController < ApplicationController
  before_action :set_practice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_partner!

  # List of all practices for that Coach
  # GET /coach_practices/1/list
  def list
    @coach = Partner.find(params[:id])
    @practices = policy_scope(Practice).where(coach_id: @coach.id).order(active: :desc, name: :asc)
  end

  # TODO: Limit this to admins
  # Probably limit to enrolled practices?
	# GET /coach_practices
  def index
    @practices = policy_scope(Practice).order("name")
  end

  def show
    @aa_hlcts = Array.new
    @practice                 = Practice.find(params[:id])
    @coach_name               = @practice.coach.name
    @visit1                   = @practice.get_inperson_visit(1)
    @visit2                   = @practice.get_inperson_visit(2)
    @visit3                   = @practice.get_inperson_visit(3)
    @visit4                   = @practice.get_inperson_visit(4)
    @visit5                   = @practice.get_inperson_visit(5)
    @qica_summary             = @practice.get_qica_summary
    action_item               = @practice.coach_items.where(item_type: CoachItem::ITEM_TYPE_VALS["Action item for practice"])
    @action_item_complete     = action_item.where(complete: true)
    @action_item_incomplete   = action_item.where(complete: false)
    coach_item                = @practice.coach_items.where(item_type: CoachItem::ITEM_TYPE_VALS["Coach follow-up"])
    @coach_item_complete      = coach_item.where(complete: true)
    @coach_item_incomplete    = coach_item.where(complete: false)
    @coach_item               = @practice.coach_items.create

    # For the last contact we want all HLCTs.  For all others we only want adopted/abandoned.
    ld = @practice.last_required_iv_contact_date
    # custom sort adopted/abandoned at the bottom
    @practice.ivcontacts.order(contact_dt: :desc).each do |ivc|
      if ivc.contact_dt == ld
        filter = "1 = 1"
      else
        filter = "test_status in (1, 2)"
      end
      ivc.high_leverage_change_tests.where(filter).each do |aa|
        @aa_hlcts << aa unless aa.description.blank?
      end
    end
  end

  # GET /coach_practices/1/edit
  def edit
    @coach_id = @practice.coach.id if @practice.coach
    # Required for New Item quick add
    @coach_item = CoachItem.new
    @visit1 = @practice.get_inperson_visit(1)
    @visit2 = @practice.get_inperson_visit(2)
    @visit3 = @practice.get_inperson_visit(3)
    @visit4 = @practice.get_inperson_visit(4)
    @visit5 = @practice.get_inperson_visit(5)
  end

  # PATCH/PUT /coach_practices/1
  # coach_practices#edit performed via Admin area - coach assignment to practices - so it should redirect
  #   to the coach list (coach_practices#index)
  def update
    coach_id = params[:coach_id]
    respond_to do |format|
      if @practice.update(:coach_id => coach_id)
        format.html { redirect_to coach_practices_path, notice: 'Practice was successfully updated.' }
        format.json { render :show, status: :ok, location: @practice }
      else
        format.html { render :edit }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practice
      @practice = Practice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def practice_params
      params[:practice].permit(:name, :address, :phone, :url, :coach_id,
        personnels_attributes: [:id, :_destroy, :name, :role, :role_other],
        coach_items_attributes: [:id, :_destroy, :item_type, :add_dt, :complete, :complete_dt,
          :notes, :practice_id])
    end
end

app/helpers/coach_practices_helper.rb
module CoachPracticesHelper

	def get_gyr_html(gyr_value)
		if Ivcontact::GYR_VALS.key(gyr_value) == "Green"
			html = "<span class='gyr-green'>Green</span>"
    elsif Ivcontact::GYR_VALS.key(gyr_value) == "Yellow"
      html = "<span class='gyr-yellow'>Yellow</span>"
 		elsif Ivcontact::GYR_VALS.key(gyr_value) == "Red"
      html = "<span class='gyr-red'>Red</span>"
    end
    return html.html_safe if html
	end

  def flag_incomplete(boo, tit = "One or more items in this section is missing a response!")
    if boo
      return raw("&nbsp;")
    else
      return image_tag("red-x.png", size: "25", title: tit)
    end
  end

  def practice_tr_style(prac)
    raw('style="background-color: darkgrey;" title="This practice has dropped from the study."') if !prac.active
  end

end

app/views/coach_practices/_comment.html.erb
<div class = "comment-<%=rowcolor%>">
  <p><%= ivc.contact_dt %></p>
  <p><%= raw(ivc.contact_comments) %></p>
</div>

app/views/coach_practices/_form.html.erb
<%= form_for(@practice, as: :practice, url: coach_practice_path(@practice), method: :patch) do |f| %>
  <% if @practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@practice.errors.count, "error") %> prohibited this practice from being saved:</h2>

      <ul>
      <% @practice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id='left-2'>
    <div>
      <%= label_tag "coach_id", "Primary Coach: " %>
      <%= select_tag "coach_id", options_for_select(policy_scope(Partner).order("name").map{ |p| [p.name, p. id] }, selected: @coach_id) %>
   </div>

    <div>
      <br />
      <h3>Required Site Visits</h3>
      <table class='lined space'>
        <tr>
          <td>Visit</td>
          <td>Date</td>
        </tr>
        <tr>
          <td>Baseline</td>
          <td><%= @visit1.try(:contact_dt) || "&mdash;".html_safe %></td>
        </tr>
        <tr>
          <td>Quarter 2</td>
          <td><%= @visit2.try(:contact_dt) || "&mdash;".html_safe %></td>
        </tr>
        <tr>
          <td>Quarter 3</td>
          <td><%= @visit3.try(:contact_dt) || "&mdash;".html_safe %></td>
        </tr>
        <tr>
          <td>Quarter 4</td>
          <td><%= @visit4.try(:contact_dt) || "&mdash;".html_safe %></td>
        </tr>
        <tr>
          <td>Quarter 5</td>
          <td><%= @visit5.try(:contact_dt) || "&mdash;".html_safe %></td>
        </tr>
      </table>
    </div>
  </div>

  <div id='right-2'>
    <% if @practice.ivcontacts.any? %>
      <h3>Intervention Contacts</h3>
      <table class='typical enable-data-table'>
        <thead>
          <tr>
            <th>Date</th>
            <th>Type</th>
          </tr>
        </thead>
        <tbody>
          <% @practice.ivcontacts.each do |c| %>
            <tr>
              <td><%= link_to c.contact_dt || "-", edit_coach_practice_ivcontact_path(@practice, c) %></td>
              <td><%= Ivcontact::CONTACT_TYPE_VALS.key(c.contact_type) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
  <div class='clearfix'></div>

    <div class="actions">
      <br />
      <%= f.submit %><br /><br />
      <%= link_to "Back", :back %>
    </div>
<% end %>

app/views/coach_practices/_item_new_popup.html.erb
<div id='popupForm'>
  <%= form_for(@coach_item) do |f| %>
    <% if @coach_item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@coach_item.errors.count, "error") %> prohibited this activity from being saved:</h2>

        <ul>
        <% @coach_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div id="closePopupForm">
      <a><%= image_tag("close.gif", alt: "Close") %></a>
    </div>
    <h3>New Action Item or Coach Follow-up</h3>
    <table class='space'>
      <tr>
        <td><%= f.label :practice_id, "Practice" %></td>
        <td colspan='4'><%= f.select :practice_id, options_for_select(policy_scope(Practice).order("name").map{ |p| [p.name, p.id] }, selected: @practice.id), include_blank: true %></td>
      </tr>
      <tr>
        <td><%= f.label :item_type, "Note Type" %></td>
        <td><%= f.select :item_type, CoachItem::ITEM_TYPE_VALS, include_blank: true %></td>
        <td>&nbsp;</td>
        <td><%= f.label :add_dt, "Date Added" %></td>
        <td><%= f.text_field :add_dt, class: 'datepicker' %> mm/dd/yyyy</td>
      </tr>
      <tr>
        <td><%= f.label :complete, "Completed?" %></td>
        <td><%= f.check_box :complete %></td>
        <td>&nbsp;</td>
        <td><%= f.label :complete_dt, "Completion Date" %></td>
        <td><%= f.text_field :complete_dt, class: 'datepicker' %> mm/dd/yyyy</td>
      </tr>
      <tr>
        <td><%= f.label :notes, "Notes" %></td>
        <td colspan='4'><%= f.text_area :notes, cols: 70, rows: 5 %></td>
      </tr>
    </table>

    <div class="actions">
      <%= f.submit "Add Note" %>
    </div>
  <% end %>
</div>

app/views/coach_practices/index.html.erb
<div id='wrapper'>
<%= render 'layouts/header' %>
<p id="notice"><%= notice %></p>

<h1>Coach Assignments by Practice</h1>

<table class='typical enable-data-table'>
  <thead>
    <tr>
      <th>Practice</th>
      <th>Coach</th>
    </tr>
  </thead>

  <tbody>
    <% @practices.each do |practice| %>
      <tr>
        <td><%= link_to practice.name, edit_coach_practice_path(practice) %></td>
        <td>
          <% if practice.coach %>
            <%= link_to practice.coach.name, list_coach_practice_path(practice.coach) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<%= link_to "Back", :back %>
</div>

app/views/coach_practices/list.html.erb
<div id='wrapper'>
<%= render 'layouts/header' %>
<p id="notice"><%= notice %></p>

<h1>Coach View for <%= @coach.name %></h1>

<table class='typical enable-data-table' data-ordering="false" data-order="[]">
  <thead>
    <tr>
      <th>Practice</th>
      <th>Randomizable?</th>
      <th>Last Required Contact</th>
      <th>EHR Vendor</th>
      <th>Last GYR Rating</th>
      <th>New Contact</th>
    </tr>
  </thead>

  <tbody>
    <% @practices.each do |practice| %>
      <tr <%= practice_tr_style(practice) %>>
        <td><%= link_to practice.name, coach_practice_path(practice) %> </td>
        <td>
          <% if practice.practice_survey %>
            <% if practice.practice_survey.status == "complete" %>
              Yes
            <% else %>
              No &ndash; practice survey not yet sent
            <% end %>
          <% else %>
            No &ndash; practice survey sent, but not yet returned
          <% end %>
        </td>
        <td>
          <% if practice.last_required_iv_contact_date && practice.last_required_iv_contact_date <= Date.today - 45 %>
            <span style="color: red;">
          <% else %>
            <span>
          <% end %>
          <%= practice.last_required_iv_contact_date %>
          </span>
        </td>
        <td><%= practice.iv_ehr_vendor %></td>
        <td>
          <%= get_gyr_html(practice.last_iv_gyr) %>
        </td>
        <td align=center><%= link_to image_tag("plus-blue.png", size: "20x20", alt: "Add New Contact"), new_coach_practice_ivcontact_path(practice), class: 'addButton', title: 'Add New Contact', rel: 'tooltip' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<%= link_to "Back", :back %>
</div>

app/views/coach_practices/show.html.erb
<div id='wrapper'>
  <%= render 'layouts/header' %>

  <div id='left-2'>
    <h1><%= @practice.name %></h1>
    <% if @practice.ivcontacts.any? %>
      <div id='required-site-visits'>
        <h3>Required Site Visits</h3>
        <table class='lined space'>
          <tr>
            <td>Visit</td>
            <td>Date</td>
          </tr>
          <tr>
            <td>Baseline</td>
            <td><%= @visit1.try(:contact_dt) || "&mdash;".html_safe %></td>
          </tr>
          <tr>
            <td>Quarter 2</td>
            <td><%= @visit2.try(:contact_dt) || "&mdash;".html_safe %></td>
          </tr>
          <tr>
            <td>Quarter 3</td>
            <td><%= @visit3.try(:contact_dt) || "&mdash;".html_safe %></td>
          </tr>
          <tr>
            <td>Quarter 4</td>
            <td><%= @visit4.try(:contact_dt) || "&mdash;".html_safe %></td>
          </tr>
          <tr>
            <td>Quarter 5</td>
            <td><%= @visit5.try(:contact_dt) || "&mdash;".html_safe %></td>
          </tr>
        </table>
      </div>
      <br />
      <div id='last-qica-results'>
        <h3>
          QICA Results from <%= @practice.iv_qica_dt.try(:strftime, '%Y-%m-%d') %>
          <% if not @practice.last_qica_complete? %>
            <span class='incomplete-warning' title='This QICA has one or more missing ratings!'>(Not Complete!)</span>
          <% end %>
        </h3>
        <table class='lined space background-green'>
          <tr>
            <th>HLC #</th>
            <th>Total Score</th>
            <th>% for HLC</th>
            <!-- <th>Missing Data?</th> -->
          </tr>
          <% @qica_summary.each.with_index do |q, idx| %>
            <tr>
              <td><%= idx + 1 %></td>
              <td><%= "#{q[0]}/#{q[2]}" %></td>
              <td><%= number_to_percentage(q[1], precision: 0) %></td>
              <!-- <td><%= flag_incomplete(q[3]) %></td> -->
            </tr>
          <% end %>
        </table>
      </div>
      <br />
      <div id='noncontinuing-hlcts'>
        <h3><abbr title = "High Leverage Change Tests">PDSA</abbr>s for this Practice</h3>
        <% if @aa_hlcts.length > 0 %>
          <table class = 'lined space background-lightpurple'>
            <thead>
              <tr>
                <th>PDSA</th>
                <th>Contact Date</th>
                <th>Status</th>
                <th>Comments</th>
              </tr>
            </thead>
            <% @aa_hlcts.each do |aa| %>
              <tr>
                <td>
                  <%= aa.description %>
                </td>
                <td style="white-space: nowrap;">
                  <%= aa.status_date %>
                </td>
                <td>
                  <%= HighLeverageChangeTest::TEST_STATUSES.key(aa.test_status) %>
                </td>
                <td>
                  <%= truncate(aa.comments, length: 100) if aa.comments %>
                </td>
              </tr>
            <% end %>
          </table>
        <% else %>
          <em>None thus far!</em>
        <% end %>
      </div>
    <% else %>
      <h3>No intervention contacts logged yet &mdash; add one on the right side of the page to make this page more interesting.</h3>
    <% end %>
  </div>

  <div id='right-2'>
    <h1>Coach: <%= @practice.coach.name if @practice.coach %></h1>
    <h2 title="Add a site contact" rel="tooltip">Site Contacts
      <%= link_to image_tag("plus-blue.png", size: "15x15"), new_coach_practice_ivcontact_path(@practice), class: 'addButton' %>
    </h2>
    <% if @practice.ivcontacts.any? %>
      <table class='typical enable-data-table' data-order='[[ 0, "desc" ]]'>
        <thead>
          <tr>
            <th>Date</th>
            <th>Type</th>
            <th>GYR</th>
            <th>Disruptions</th>
          </tr>
        </thead>
        <tbody>
          <% @practice.ivcontacts.order(contact_dt: :desc).each do |c| %>
            <tr>
              <td><%= link_to c.contact_dt || "-", edit_coach_practice_ivcontact_path(@practice, c) %></td>
              <td><%= Ivcontact::CONTACT_TYPE_VALS.key(c.contact_type) %></td>
              <td><%= get_gyr_html(c.gyr) %></td>
              <td><%= c.disruptions %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <em style="color: red;">Click the + icon above to add your first contact.</em>
      <br /><br />
    <% end %>
    <button id="coach-practice-comment-opener">View Contact Comments</button>

    <br />
    <% if @practice.ivcontacts.any? %>
      <div class='box'>
        <div id='openPopupForm'>
          <h2 title="Coach Notes" rel="tooltip">Coach Notes
            <a class='addButton' title="Add New Item" rel="tooltip">
              <%= image_tag("plus-blue.png", size: "15x15") %>
            </a>
          </h2>
        </div>
        <%= render partial: 'item_new_popup' %>
        <h3>Action Items for Practice</h3>
        <div id='tabs-item'>
          <ul>
            <li><a href="#tabs-item-incomplete">Incomplete</a></li>
            <li><a href="#tabs-item-complete">Complete</a></li>
          </ul>
          <div id='tabs-item-incomplete'>
          <table class='typical enable-data-table'>
            <thead>
              <tr>
                <th>Date</th>
                <th>Notes</th>
              </tr>
            </thead>
            <tbody>
              <% @action_item_incomplete.each do |i| %>
                <tr>
                  <td><%= link_to i.add_dt || "-", edit_coach_practice_coach_item_path(@practice, i) %></td>
                  <td><%= truncate(i.notes, length: 255) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          </div>
          <div id='tabs-item-complete'>
          <table class='typical enable-data-table'>
            <thead>
              <tr>
                <th>Date</th>
                <th>Notes</th>
              </tr>
            </thead>
            <tbody>
              <% @action_item_complete.each do |i| %>
                <tr>
                  <td><%= link_to i.add_dt || "-", edit_coach_practice_coach_item_path(@practice, i) %></td>
                  <td><%= truncate(i.notes, length: 255) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          </div>
        </div>

        <br />
        <h3>Coach Follow-ups</h3>
        <div id='tabs-fu'>
          <ul>
            <li><a href="#tabs-fu-incomplete">Incomplete</a></li>
            <li><a href="#tabs-fu-complete">Complete</a></li>
          </ul>
          <div id='tabs-fu-incomplete'>
            <table class='typical enable-data-table'>
              <thead>
                <tr>
                  <th>Add Date</th>
                  <th>Notes</th>
                </tr>
              </thead>
              <tbody>
                <% @coach_item_incomplete.each do |i| %>
                  <tr>
                    <td><%= link_to i.add_dt || "-", edit_coach_practice_coach_item_path(@practice, i) %></td>
                    <td><%= truncate(i.notes, length: 255) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div id='tabs-fu-complete'>
            <table class='typical enable-data-table'>
              <thead>
                <tr>
                  <th>Add Date</th>
                  <th>Notes</th>
                </tr>
              </thead>
              <tbody>
                <% @coach_item_complete.each do |i| %>
                  <tr>
                    <td><%= link_to i.add_dt || "-", edit_coach_practice_coach_item_path(@practice, i) %></td>
                    <td><%= truncate(i.notes, length: 255) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    <%end %>
  </div>
  <div id = 'contact-comments' title="Comments from All Contacts">
    <% if @practice.ivcontacts.any? then %>
      <% rowcolor = 1 %>
      <% @practice.ivcontacts.order('contact_dt desc').each do |ivc| %>
        <p><%= render :partial => 'comment', :locals => {:ivc => ivc, :rowcolor => rowcolor} %></p>
        <% rowcolor = 1 - rowcolor %>
      <% end %>
    <% else %>
      <p>None yet &mdash; add some contacts.</p>
    <% end %>
  </div>

  <div class='clearfix'>

  </div>

  <div class="actions">
    <br />
    <%= link_to "Back", :back %>
  </div>

</div>