config/routes.rb
Rails.application.routes.draw do

  resources :manager_notes
  devise_for :partners
  devise_scope :partners do
    get  'partners/admin_new' => 'partners#admin_new'
    post 'partners/admin_create' => 'partners#admin_create'
  end

  resource :mains, only: :index
  get 'practice_survey_thanks', to: 'mains#practice_survey_thanks'
  get 'admin_area', to: 'mains#admin_area'
  get 'supervisor_area', to: 'mains#supervisor_area'
  get 'practice_contacts', to: 'mains#practice_contacts'
  get 'practice_progress', to: 'mains#practice_progress'
  get 'survey_progress', to: 'mains#survey_progress'
  get 'practice_lifetime/:id', to: 'mains#practice_lifetime', as: 'practice_lifetime'
  get 'qualitative_export', to: 'ivcontacts#qualitative_export'

  resources :surveys do
    collection do
      post :import
      get :import_results
    end
  end
  get 'practice_survey_practices', to: 'surveys#practice_survey_practices'
  get 'staff_survey_practices', to: 'surveys#staff_survey_practices'

  resources :sites do
    resources :partners
  end
  resources :partners do
    resources :events
    resources :practices
    get 'list', on: :collection
    get 'assign_practice', on: :member
  end
  resources :practices do
    resources :events
    resources :personnels
    get 'export', on: :collection
  end
  resources :coach_practices do
    resources :ivcontacts
    resources :coach_items
    get 'list', on: :member
  end
  resources :ivcontacts do
    resources :high_leverage_change_tests
  end
  resources :coach_assignments, only: [ :index, :edit, :update ]
  resources :events
  resources :personnels
  resources :practice_surveys
  resources :high_leverage_change_tests
  resources :coach_items
  resources :dropouts, only: [ :index, :edit, :update ]

  root 'mains#index'
  as :partner do
    get 'partners', :to => 'partners#show', :as => :partner_root
  end

end

app/controllers/coach_assignments_controller.rb
class CoachAssignmentsController < ApplicationController
  before_action :authenticate_partner!

  def index
    @coaches = policy_scope(Partner).order(:name).all
    respond_to do |format|
      format.html
      format.csv
    end
  end

	# GET /coach_assignments/1/edit
  def edit
  	@coach = Partner.find(params[:id])
  	@practices = policy_scope(Practice).where(coach_id: @coach.id).order(:name)
  	@practices_unselected = policy_scope(Practice).where("pal_status_cached = 'Returned' AND (coach_id != ? or coach_id IS NULL)", @coach.id)
  end

  # PATCH/PUT /coach_assignments/1
  # PATCH/PUT /coach_assignments/1.json
  def update
    @coach = Partner.find(params[:id])
    success = true
    Practice.where(coach_id: @coach.id).update_all(coach_id: nil)
  	params[:practice_id].reject(&:empty?).each do |i|
      success = Practice.find(i).update(coach_id: @coach.id)
    end
    respond_to do |format|
      if success
        format.html { redirect_to edit_coach_assignment_path(@coach),
          notice: 'Practice assignments were successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
end

app/helpers/coach_assignments_helper.rb
module CoachAssignmentsHelper
end

app/views/coach_assignments/_assigned_practice_fields.html.erb
<tr class='deletable'>
  <td><%= select_tag "practice_id[]", options_for_select(policy_scope(Practice).order("name").collect { |p| [p.name, p.id] }, selected: practice.id) %></td>
  <td style="text-align: center;"><% if practice.last_required_iv_contact && (practice.last_required_iv_contact_date <= Date.today - 45) %>
        <span style="color: red;">
      <% else %>
        <span>
      <% end %>
      <%= practice.last_required_iv_contact_date %>
      </span>
  </td>
  <td style="text-align: center;"><%= practice.last_iv_status %></td>
  <td style="text-align: center;"><%= link_to image_tag("view.png", size: "20x20"), coach_practice_path(practice) %></td>
  <td style="text-align: center;"><%= image_tag "minus-blue.png", height: 15, width: 15, class: "delete-practice-assignment-button", alt: "Delete Practice", title: "Delete Practice" %></td>
</tr>

app/views/coach_assignments/edit.html.erb
<%= form_tag(coach_assignment_path(@coach), method: :patch) do |f| %>
  <div id='wrapper'>
  <%= render 'layouts/header' %>
  <p id="notice"><%= notice %></p>

  <h1>Practice Assignment for <%= @coach.name %></h1>

  <table class='space' id='assign-practice-table'>
    <thead>
      <tr>
        <th>Practice</th>
        <th>Last Required Contact</th>
        <th>Status</th>
        <th>Coach View of Practice</th>
        <th>Unassign Practice</th>
      </tr>
    </thead>

    <tbody>
      <% @practices.each do |practice| %>
        <%= render 'assigned_practice_fields', :practice => practice %>
      <% end %>
      <tr id='add-practice-assignment-row'>
        <td colspan="5">
        	<span title="Assign New Practice">Add Practice <%= image_tag "plus-blue.png", height: 15, width: 15, id: "add-practice-assignment-button" %></span>
        </td>
      </tr>
    </tbody>
  </table>

  <br />
  <div>
    <%= submit_tag "Save" %>
  </div>

<% end %>

<table style="display:none;">
  <tbody id='add-practice-assignment-section'>
    <tr class='deletable'>
      <td><%= select_tag "practice_id[]", options_for_select(@practices_unselected.order("name").collect { |p| [p.name, p.id] }), include_blank: true %></td>
      <td>&mdash;</td>
      <td>&mdash;</td>
      <td>View</td>
      <td><%= image_tag "minus-blue.png", height: 15, width: 15, class: "delete-practice-assignment-button", alt: "Delete Practice", title: "Delete Practice" %></td>
    </tr>
  </tbody>
</table>

<br />
<br />
<%= link_to "Return to Coaches List", coach_assignments_path %>

<br />
<br />
<%= link_to "Back", :back %>
</div>

app/views/coach_assignments/index.html.erb
<div id='wrapper'>
<%= render 'layouts/header' %>

<h1>Coaches and Coach Assignments</h1>

<table class='typical enable-data-table'>
  <thead>
    <tr>
      <th>Coach</th>
      <th>Coach View of Practice</th>
      <th>Assign Practices</th>
    </tr>
  </thead>

  <tbody>
    <% @coaches.each do |coach| %>
      <tr>
        <td><%= coach.name %></td>
        <td style="text-align: center;"><%= link_to image_tag("view.png", size: "20x20"), list_coach_practice_path(coach) if Practice.exists?(coach_id: coach.id) %></td>
        <td style="text-align: center;"><%= link_to image_tag("plus-arrow-blue.png", size: "40x20"), edit_coach_assignment_path(coach) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to "Back", :back %>
</div>