config/routes.rb
Rails.application.routes.draw do

  resources :manager_notes
  devise_for :partners
  devise_scope :partners do
    get  'partners/admin_new' => 'partners#admin_new'
    post 'partners/admin_create' => 'partners#admin_create'
  end

  resource :mains, only: :index
  get 'practice_survey_thanks', to: 'mains#practice_survey_thanks'
  get 'admin_area', to: 'mains#admin_area'
  get 'supervisor_area', to: 'mains#supervisor_area'
  get 'practice_contacts', to: 'mains#practice_contacts'
  get 'practice_progress', to: 'mains#practice_progress'
  get 'survey_progress', to: 'mains#survey_progress'
  get 'practice_lifetime/:id', to: 'mains#practice_lifetime', as: 'practice_lifetime'
  get 'qualitative_export', to: 'ivcontacts#qualitative_export'

  resources :surveys do
    collection do
      post :import
      get :import_results
    end
  end
  get 'practice_survey_practices', to: 'surveys#practice_survey_practices'
  get 'staff_survey_practices', to: 'surveys#staff_survey_practices'

  resources :sites do
    resources :partners
  end
  resources :partners do
    resources :events
    resources :practices
    get 'list', on: :collection
    get 'assign_practice', on: :member
  end
  resources :practices do
    resources :events
    resources :personnels
    get 'export', on: :collection
  end
  resources :coach_practices do
    resources :ivcontacts
    resources :coach_items
    get 'list', on: :member
  end
  resources :ivcontacts do
    resources :high_leverage_change_tests
  end
  resources :coach_assignments, only: [ :index, :edit, :update ]
  resources :events
  resources :personnels
  resources :practice_surveys
  resources :high_leverage_change_tests
  resources :coach_items
  resources :dropouts, only: [ :index, :edit, :update ]

  root 'mains#index'
  as :partner do
    get 'partners', :to => 'partners#show', :as => :partner_root
  end

end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :set_practice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_partner!

  # GET /practices
  # GET /practices.json
  def index
    @practices = policy_scope(Practice).includes(:primary_contacts, :ehr_helpers, :ehr_extractors, :site, :partners).all
    respond_to do |format|
      format.html
      format.csv
    end
  end

  def export
    export_name = 'practices.csv'
    @practices = policy_scope(Practice).all
    response.headers['Content-Type'] = 'text/event-stream'
    response.headers['Content-Disposition'] = "attachment; filename=#{export_name}"
    render :template => 'practices/export.csv.erb'
  ensure
    response.stream.close
  end

  # GET /practices/1
  # GET /practices/1.json
  def show
    @personnel = Personnel.new
  end

  # GET /practices/new
  def new
    @practice = Practice.new
    @partner_id = params[:partner_id]
  end

  # GET /practices/1/edit
  def edit
    @recruiter_id = @practice.recruiter.id if @practice.recruiter

    Practice::REQUIRED_FOR_RANDOMIZATION.keys.each do |fld|
      if @practice.send(fld).nil? then
        @practice.errors.add(fld, " is required for randomization.")
      end
    end
  end

  # POST /practices
  # POST /practices.json
  def create
    @practice = Practice.new(practice_params)
    if params[:recruiter_partner].present?
      @partner = Partner.find(params[:recruiter_partner])
      @practice.partners << @partner
    end

    @practice.site_id = @current_partner.site.id

    respond_to do |format|
      if @practice.save
        format.html { redirect_to partner_path(current_partner), notice: 'Practice was successfully created.' }
        format.json { render :show, status: :created, location: @practice }
      else
        format.html { render :new }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practices/1
  # PATCH/PUT /practices/1.json
  def update
    respond_to do |format|
      if @practice.update(practice_params)
        # Delete the currently associated partner
        if params[:original_recruiter].present?
          delete_sql = "DELETE FROM partners_practices WHERE " +
            "partner_id = #{params[:original_recruiter]} AND practice_id = #{@practice.id};"
          ActiveRecord::Base.connection.execute delete_sql
        end
        # Add the new associated partner (if any)
        if params[:recruiter_partner].present?
          insert_sql = "INSERT INTO partners_practices (partner_id, practice_id) " +
            "VALUES (#{params[:recruiter_partner]}, #{@practice.id});"
          ActiveRecord::Base.connection.execute insert_sql
        end
        format.html { redirect_to partner_path(current_partner), notice: 'Practice was successfully updated.' }
        format.json { render :show, status: :ok, location: @practice }
      else
        format.html { render :edit }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practices/1
  # DELETE /practices/1.json
  def destroy
    @practice.destroy
    respond_to do |format|
      format.html { redirect_to practices_url, notice: 'Practice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practice
      @practice = Practice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def practice_params
      params[:practice].permit(:name, :address, :phone, :url,
        :primary_care, :email, :parent_organization,
        :prac_ehr_yr, :prac_ehr, :prac_ehrname, :prac_ehrversion,
        :prac_ehrname_other, :prac_ehr_mu, :prac_mu_stage1, :prac_mu_stage2,
        :prac_ehr_extractdata, :prac_ehr_person_extractdata,
        :prac_ehr_person_extractdata_other, :prac_it_support,
        :prac_ehr_vendor, :prac_share_healthinfo, :prac_cqm,
        :prac_cqm_submit, :prac_cqm_who, :prac_ehr_satisfaction,
        :prac_new_ehr, :elig_phys_count, :elig_phys_fte,
        :number_clinicians, :fte_clinicians,
        :prac_own_other_specify, :prac_own_yrs,
        :elig_clinic_count, :prac_spec_mix, :prac_pcmh,
        :prac_aco_join_medicaid, :interest_why, :interest_expect,
        :interest_challenge, :recruitment_source, :recruitment_source_referral,
        :prac_ehr_mu_yr, :interest_yn, :interest_why_not, :interest_why_not_other,
        :interest_contact_month, :prac_state, :site_id, :prac_own_clinician,
        :prac_own_hosp, :prac_own_hmo, :prac_own_fqhc, :prac_own_nonfed, :prac_own_academic,
        :prac_own_fed, :prac_own_rural, :prac_own_ihs, :prac_own_other,
        :prac_aco_medicaid, :prac_aco_medicare, :prac_aco_commercial,
        :prac_aco_other, :prac_aco_none, :prac_aco_dk,
        :prac_aco_join_medicare, :prac_aco_join_commercial,
        :zip_code, :city, :residency_training_site, :eligibility_exception,
        personnels_attributes: [:id, :_destroy, :name, :role, :role_other, :phone1,
          :phone1_best, :phone2, :phone2_best, :email1, :email1_best,
          :email2, :email2_best, :ehr_extractor, :ehr_helper, :ehr_cqm,
          :site_contact_primary, :site_contact_secondary, :site_contact_champion])
    end
end

app/helpers/practices_helper.rb
module PracticesHelper
  require 'csv'

  def check_practice_cache
    agree_count = 0
    problem_practices = Array.new
    prob_list = ""
    Practice.all.each do |p|
      if p.la_date_cached == p.last_contact and (p.pal_status_cached || "") == p.pal_status and (p.pc_name_cached || "") == (p.primary_contact || "")
        agree_count += 1
      else
        problem_practices << p
      end
    end
    problem_practices.each do |p|
      prob_list << "#{p.id}: Last activity: cache: #{p.la_date_cached}, actual: #{p.last_contact}\n" unless p.la_date_cached == p.last_contact
      prob_list << "#{p.id}: PAL status: cache: #{p.pal_status_cached}, actual: #{p.pal_status}\n" unless (p.pal_status_cached || "") == p.pal_status
      prob_list << "#{p.id}: Primary Contact: cache: #{p.pc_name_cached}, actual: #{p.primary_contact}\n" unless (p.pc_name_cached || "") == (p.primary_contact || "")
    end
    puts prob_list
    puts "All OK for #{agree_count} practices.  There were problems for #{problem_practices.length} practices."
  end

  def export(practices)
    to_export = {
                  id:                           'Database ID',
                  study_id:                     'Practice ID',
                  name:                         'Practice Name',
                  coach_name:                   'Coach Name',
                  enrolled:                     'Enrolled?',
                  interest_yn:                  'Interested?',
                  status:                       'Recruitment Status',
                  pal_status_cached:            'PAL Status',
                  la_date_cached:               'Last Activity',
                  parent_organization:          'Parent Org',
                  current_partner:              'Primary Recruiter',
                  recruitment_source:           'Recruitment Source',
                  address:                      'Practice Address',
                  city:                         'Practice City',
                  prac_state:                   'Practice State',
                  zip_code:                     'Practice Zip',
                  phone:                        'Practice Phone',
                  url:                          'Practice Website',
                  email:                        'Practice E-mail',
                  residency_training_site:      'Residency Training Site?',
                  interest_yn:                  'Interested?',
                  interest_why_not:             'Why not interested?',
                  interest_why:                 'Why interested?',
                  interest_expect:              'Expected outcomes',
                  interest_challenge:           'Expected challenges',
                  interest_contact_month:       'Good month for coach visit?',
                  primary_care:                 'Primary Care',
                  number_clinicians:            'No. clinicians',
                  fte_clinicians:               'Clinician FTE',
                  prac_ehr:                     'EHR',
                  prac_ehr_mu:                  'MU-certified?',
                  prac_ehr_mu_yr:               'Year Certified',
                  prac_own_clinician:           'Clinician owned?',
                  prac_own_hosp:                'Hosp/healthsys owned?',
                  prac_own_hmo:                 'HMO Owned?',
                  prac_own_fqhc:                'FQHC Owned?',
                  prac_own_nonfed:              'Nonfed Govt Owned?' ,
                  prac_own_academic:            'Academic Owned?',
                  prac_own_fed:                 'Federal Owned?',
                  prac_own_rural:               'Rural Owned?',
                  prac_own_ihs:                 'IHS Owned?',
                  prac_own_other:               'Other Owned',
                  prac_own_other_specify:       'Other - specify',
                  prac_own_yrs:                 'Years Current Ownership',
                  elig_clinic_count:            'No. Clinics Owned by Parent Org',
                  prac_spec_mix:                'Specialty Mix',
                  prac_pcmh:                    'PCMH?',
                  prac_aco_medicaid:            'Medicaid ACO',
                  prac_aco_medicare:            'Medicare ACO' ,
                  prac_aco_commercial:          'Private/Commercial ACO',
                  prac_aco_other:               'Other ACO',
                  prac_aco_dk:                  "Don't Know ACO",
                  prac_aco_none:                'Not an ACO',
                  prac_aco_join_medicaid:       'Join Medicaid ACO?',
                  prac_aco_join_medicare:       'Join Medicare ACO?',
                  prac_aco_join_commercial:     'Join Pvt/Commercial ACO?',
                  prac_ehr_extractdata:         'Have data extractor?',
                  prac_ehr_person_extractdata:  'Data Extractor',
                  prac_ehr_person_extractdata_other: 'DE--other',
                  prac_it_support:              'Have HIT support?',
                  prim_con_name:                'Primary Contact',
                  prim_con_phone:               'Primary Contact Phone',
                  prim_con_email:               'Primary Contact Email',
                  ehr_ext_name:                 'EHR Extractor',
                  ehr_ext_phone:                'EHR Extractor Phone',
                  ehr_ext_email:                'EHR Extractor Email',
                  ehr_hlp_name:                 'EHR Helper',
                  ehr_hlp_phone:                'EHR Helper Phone',
                  ehr_hlp_email:                'EHR Helper Email',
                  site_id:                      'Site',
                  active:                       'Active in Project?',
                  inactive_rsn:                 'Reason for dropping',
                  drop_dt:                      'Date dropped',
                  drop_reentry_dt:              'Date re-entered project',
                  drop_determine:               'Drop determined by',
                  drop_contact_who:             'Drop practice contact',
                  drop_notify_who:              'Who notified of the drop?',
                  drop_notify_how:              'Drop notification method',
                  drop_notify_dt:               'Date of drop notification',
                  drop_notify_rsn_demanding:    'Reason for drop: too demanding',
                  drop_notify_rsn_priority:     'Reason for drop: other priorities',
                  drop_notify_rsn_barrier:      'Reason for drop: barrier',
                  drop_notify_rsn_relevant:     'Reason for drop: H2N not useful',
                  drop_notify_rsn_other:        'Reason for drop: other',
                  drop_notify_rsn_specify:      'Reason for drop: specify',
                  drop_decide_who:              'Staff member dropping',
                  drop_decide_why:              'Staff member reason',
                  drop_comments:                'Drop Comments',
                }

    csv_string = CSV.generate do |csv|
      csv << to_export.values
      practices.all.each do |prac|
        prim_con  = prac.primary_contacts.first
        ehr_ext   = prac.ehr_extractors.first
        ehr_hlp   = prac.ehr_helpers.first
        # TODO: ? Add QI Champion.
        wanted_attributes = Hash.new
        to_export.keys.each do |k|
          wanted_attributes[k] = case k
                                  when :enrolled
                                    (prac.pal_status_cached == 'Returned')
                                  when :prac_state
                                    Practice::PRAC_STATE_VALS.key(prac.send(k))
                                  when :prac_ehr
                                    Practice::PRAC_EHR_VALS.key(prac.send(k))
                                  when :recruitment_source
                                    Practice::RECRUITMENT_SOURCE_VALS.key(prac.send(k))
                                  when :primary_care, :interest_yn, :prac_ehr_mu, :prac_pcmh
                                    Practice::YN12_VALS.key(prac.send(k))
                                  when :interest_why_not
                                    Practice::INTEREST_WHY_NOT_VALS.key(prac.send(k))
                                  when :interest_contact_month
                                    Practice::INTEREST_CONTACT_MONTH_VALS.key(prac.send(k))
                                  when :prac_spec_mix
                                    Practice::PRAC_SPEC_MIX_VALS.key(prac.send(k))
                                  when :prac_ehr_extractdata
                                    Practice::PRAC_EHR_EXTRACTDATA_VALS.key(prac.send(k))
                                  when :prac_ehr_person_extractdata
                                    Practice::PRAC_EHR_PERSON_EXTRACTDATA_VALS.key(prac.send(k))
                                  when :prac_aco_join_medicaid
                                    Practice::PRAC_ACO_JOIN_MEDICAID_VALS.key(prac.send(k))
                                  when :prac_aco_join_medicare
                                    Practice::PRAC_ACO_JOIN_MEDICARE_VALS.key(prac.send(k))
                                  when :prac_aco_join_commercial
                                    Practice::PRAC_ACO_JOIN_COMMERCIAL_VALS.key(prac.send(k))
                                  when :prac_it_support
                                    Practice::PRAC_IT_SUPPORT_VALS.key(prac.send(k))
                                  when :site_id
                                    prac.site ? prac.site.name : 'Not assigned'
                                  when :prim_con_name
                                    prim_con.name if prim_con
                                  when :prim_con_phone
                                    prim_con.phone1 if prim_con
                                  when :prim_con_email

app/views/practices/_personnel_fields.html.erb
<div class='nested-fields box'>
  <table class='space'>
    <tr>
      <td><%= f.label :name %></td>
      <td colspan='3'><%= f.text_field :name %></td>
      <td><%= f.label :role %></td>
      <td><%= f.select :role, Personnel::ROLE_VALS, include_blank: true %></td>
      <td>
        <%= f.label :role_other, "Specify: " %><%= f.text_field :role_other, size: 10 %>
      </td>
    </tr>
    <tr>
      <td><%= f.label :phone1, "Phone 1" %></td>
      <td><%= f.text_field :phone1 %></td>
      <td>Best Contact? <%= f.check_box :phone1_best %></td>
      <td>&nbsp;</td>
      <td><%= f.label :email1, "Email 1" %></td>
      <td><%= f.text_field :email1 %></td>
      <td>Best Contact? <%= f.check_box :email1_best %></td>
    </tr>
    <tr>
      <td><%= f.label :phone2, "Phone 2" %></td>
      <td><%= f.text_field :phone2 %></td>
      <td>Best Contact? <%= f.check_box :phone2_best %></td>
      <td>&nbsp;</td>
      <td><%= f.label :email2, "Email 2" %></td>
      <td><%= f.text_field :email2 %></td>
      <td>Best Contact? <%= f.check_box :email2_best %></td>
    </tr>
    <tr>
      <td colspan='7'>
        <table>
          <tr>
            <td>H2N Roles:</td>
            <td><%= f.label :site_contact_primary, "Primary Site Contact" %></td>
            <td><%= f.check_box :site_contact_primary %></td>
            <td><%= f.label :site_contact_secondary, "Secondary Site Contact" %></td>
            <td><%= f.check_box :site_contact_secondary %></td>
            <td><%= f.label :site_contact_champion, "QI Champion" %></td>
            <td><%= f.check_box :site_contact_champion %></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td colspan='7'>
        <table>
          <tr>
            <td>EHR Duties:</td>
            <td><%= f.label :ehr_extractor, "Configure & Write EHR Reports" %></td>
            <td><%= f.check_box :ehr_extractor %></td>
            <td><%= f.label :ehr_helper, "Help with EHR Problems" %></td>
            <td><%= f.check_box :ehr_helper %></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td colspan='7'><%= link_to_remove_association "Delete Staff Member", f %></td>
    </tr>
  </table>
</div>

app/views/practices/assign_practice.html.erb
<div id='wrapper'>
<%= render 'layouts/header' %>
<p id="notice"><%= notice %></p>

<h1>Practice Assignment for <%= @coach.name %></h1>

<table class='space'>
  <thead>
    <tr>
      <th>Practice</th>
      <th>Last Required Contact</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @practice_current.each do |practice| %>
      <tr>
      	<td><%= select_tag :practice_id, options_for_select(policy_scope(Practice).order("name").collect { |p| [p.name, p.id] }, selected: practice.id) %></td>
        <td>
          <% if practice.last_required_iv_contact && practice.last_required_iv_contact_date <= Date.today - 45 %>
            <span style="color: red;">
          <% else %>
            <span>
          <% end %>
          <%= practice.last_required_iv_contact_date %>
          </span>
        </td>
        <td><%= practice.last_iv_status %></td>
        <td><%= link_to "Edit", coach_practice_path(practice) %></td>
        <td><%= image_submit_tag "minus-blue.png", height: 15, width: 15, id: "delete-practice-assignment-button", alt: "Delete Practice" %>Can I add a tooltip instead of text?</td>
      </tr>
    <% end %>
    <tr>
      <td colspan="5">
      	Add Practice <%= image_submit_tag "plus-blue.png", height: 15, width: 15, id: "add-practice-assignment-button" %>Can I add a tooltip instead of text?
      </td>
    </tr>
  </tbody>
</table>

<br />
<%= link_to "Back", :back %>
</div>

app/views/practices/edit.html.erb
<div id='wrapper'>
<%= render 'layouts/header' %>

<div id='left-2'>
	<h1>Editing <%= @practice.name %></h1>
</div>

<div id='right-2'>
	<h1>Status: <%= @practice.status %></h1><br />
</div>

<div class='clearfix'></div>

<%= render 'form' %>
</div>

app/views/practices/export.csv.erb
<%= raw(export(@practices)) %>

app/views/practices/index.csv.erb
<%= raw(export(@practices)) %>

app/views/practices/index.html.erb
<div id='wrapper'>
<%= render 'layouts/header' %>

<h1>Practices</h1>

<table class='typical enable-data-table'>
  <thead>
    <tr>
      <th>Practice</th>
      <th>Site</th>
      <th>Practice ID</th>
      <th>Recruiter</th>
      <th>Coach</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @practices.each do |practice| %>
      <tr>
        <td><%= link_to practice.name, edit_practice_path(practice) %></td>
        <td><%= practice.site.name if practice.site %></td>
        <td><%= practice.study_id if practice.study_id %></td>
        <td><%= practice.recruiter.name if practice.recruiter %></td>
        <td><%= practice.coach.name if practice.coach %></td>
        <td>
          <% if practice.active == false %>
            <%= link_to "Re-enter", edit_dropout_path(practice) %>
          <% elsif practice.active == true %>
            <%= link_to "Drop out", edit_dropout_path(practice) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'Add New Practice', new_practice_path %>
<br />
<br />
<%= link_to "Back", :back %>
</div>

app/views/practices/new.html.erb
<div id='wrapper'>
<%= render 'layouts/header' %>

<h1>New Practice</h1>

<%= render 'form' %>
</div>

app/views/practices/show.html.erb
<div id='wrapper'>
<%= render 'layouts/header' %>

<div id='left-13'>
  <h2> <%= @practice.name %>
    <%= link_to image_tag("arrow-blue.png", size: "15x15"), edit_practice_path(@practice), class: 'addButton', title: 'Edit Practice', rel: 'tooltip' %>
  </h2>
  <table class='space'>
    <tr>
      <td> Primary Recruiter </td>
      <td><%= @practice.pc_name_cached %></td>
    </tr>
    <tr>
      <td> Address </td>
      <td> <%= link_to @practice.address, "https://maps.google.com/maps?q=#{@practice.address}", :target => '_blank' %> </td>
    </tr>
    <tr>
      <td>Phone</td>
      <td> <%= @practice.phone %></td>
    </tr>
    <tr>
      <td>URL</td>
      <td><%= link_to @practice.url, @practice.url, :target => '_blank' %></td>
    </tr>
  </table>

  <div id='openPopupForm' class='extraTopSpace'>
    <h3>Staff
      <a class='addButton' title="Add New Staff" rel="tooltip">
        <%= image_tag("plus-blue.png", size: "15x15") %>
      </a>
    </h3>
  </div>
  <div id='popupForm' class='popupForm-large'>
    <%= form_for([@practice, @personnel]) do |f| %>
      <% if @personnel.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@personnel.errors.count, "error") %> prohibited this appointment from being saved:</h2>

          <ul>
          <% @personnel.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div id="closePopupForm">
        <a><%= image_tag("close.gif", alt: "Close") %></a>
      </div>
      <h3>Add Staff</h3>
      <%= f.hidden_field :practice_id, value: @practice.id %>
      <table class='space'>
        <tr>
          <td><%= f.label :name %></td>
          <td colspan='2'><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td><%= f.label :role %></td>
          <td><%= f.select :role, Personnel::ROLE_VALS, include_blank: true %></td>
        </tr>
        <tr>
          <td><%= f.label :phone1, "Phone 1" %></td>
          <td><%= f.text_field :phone1 %></td>
          <td>Best Contact? <%= f.check_box :phone1_best %></td>
        </tr>
        <tr>
          <td><%= f.label :email1, "Email 1" %></td>
          <td><%= f.text_field :email1 %></td>
          <td>Best Contact? <%= f.check_box :email1_best %></td>
        </tr>
        <tr>
          <td><%= f.label :phone2, "Phone 2" %></td>
          <td><%= f.text_field :phone2 %></td>
          <td>Best Contact? <%= f.check_box :phone2_best %></td>
        </tr>
        <tr>
          <td><%= f.label :email2, "Email 2" %></td>
          <td><%= f.text_field :email2 %></td>
          <td>Best Contact? <%= f.check_box :email2_best %></td>
        </tr>
      </table>
      <div class="actions">
        <%= f.submit "Add Staff" %>
      </div>
    <% end %>
  </div>

  <% if @practice.personnels.any? %>
    <table class='typical enable-data-table'>
      <thead>
      <tr>
          <th>Name</th>
          <th>Role</th>
          <th>Best Contact</th>
        </tr>
      </thead>
      <tbody>
        <% @practice.personnels.order("name").each do |p| %>
          <tr>
            <td><%= link_to p.name, edit_practice_personnel_path(@practice, p) %></td>
            <td><%= p.role %></td>
            <td><%= p.best_contact %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p> No staff noted. </p>
  <% end %>
</div>

<div id='right-23'>
  <h3> Activity Log <%= link_to image_tag("plus-arrow-blue.png", size: "30x15", alt: "Schedule New Event"), new_practice_event_path(@practice), class: 'addButton', title: 'Add New Contact', rel: 'tooltip' %>
  </h3>
  <% if @practice.events.any? %>
    <table class='typical enable-data-table'>
      <thead>
        <tr>
          <th>Date</th>
          <th>Time</th>
          <th>Recruiter</th>
          <th>Mode</th>
          <th>Outcome</th>
          <th>Notes</th>
        </tr>
      </thead>
      <tbody>
        <% @practice.events.order("schedule_dt, schedule_tm").each do |e| %>
          <tr>
            <td><%= link_to e.schedule_dt.try(:strftime, "%-m/%-d/%Y"), practice_event_path(@practice, e) %></td>
            <td><%= e.schedule_tm.try(:strftime, "%l:%M %p") %></td>
            <td><%= e.partner.name %></td>
            <td><%= Event::CONTACT_TYPE_VALS.key(e.contact_type) %></td>
            <td><%= Event::OUTCOME_VALS.key(e.outcome) %></td>
            <td><%= truncate(e.description, length: 75) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p> No events exist. </p>
  <% end %>
</div>

<div class='clearfix'></div>

<%= link_to "Back", :back %>
</div>