config/routes.rb
Rails.application.routes.draw do

  resources :manager_notes
  devise_for :partners
  devise_scope :partners do
    get  'partners/admin_new' => 'partners#admin_new'
    post 'partners/admin_create' => 'partners#admin_create'
  end

  resource :mains, only: :index
  get 'practice_survey_thanks', to: 'mains#practice_survey_thanks'
  get 'admin_area', to: 'mains#admin_area'
  get 'supervisor_area', to: 'mains#supervisor_area'
  get 'practice_contacts', to: 'mains#practice_contacts'
  get 'practice_progress', to: 'mains#practice_progress'
  get 'survey_progress', to: 'mains#survey_progress'
  get 'practice_lifetime/:id', to: 'mains#practice_lifetime', as: 'practice_lifetime'
  get 'qualitative_export', to: 'ivcontacts#qualitative_export'

  resources :surveys do
    collection do
      post :import
      get :import_results
    end
  end
  get 'practice_survey_practices', to: 'surveys#practice_survey_practices'
  get 'staff_survey_practices', to: 'surveys#staff_survey_practices'

  resources :sites do
    resources :partners
  end
  resources :partners do
    resources :events
    resources :practices
    get 'list', on: :collection
    get 'assign_practice', on: :member
  end
  resources :practices do
    resources :events
    resources :personnels
    get 'export', on: :collection
  end
  resources :coach_practices do
    resources :ivcontacts
    resources :coach_items
    get 'list', on: :member
  end
  resources :ivcontacts do
    resources :high_leverage_change_tests
  end
  resources :coach_assignments, only: [ :index, :edit, :update ]
  resources :events
  resources :personnels
  resources :practice_surveys
  resources :high_leverage_change_tests
  resources :coach_items
  resources :dropouts, only: [ :index, :edit, :update ]

  root 'mains#index'
  as :partner do
    get 'partners', :to => 'partners#show', :as => :partner_root
  end

end

app/models/survey.rb
# t.references :practice
# t.string :survey_type
# t.int :administration
# t.date :date_sent
# t.string :status
# t.float :percent_complete

class Survey < ActiveRecord::Base

  belongs_to :practice

  def self.write_abcs(row, practice, result)
    # Create additional survey records for any ABCSs
    # CHANGE TO FIRST DAY AFTER THE QUARTER
    abcs_fields = { :q20154 => Date.new(2015, 9, 1),
                    :q20161 => Date.new(2016, 1, 1),
                    :q20162 => Date.new(2016, 3, 1),
                    :q20163 => Date.new(2016, 6, 1),
                    :q20164 => Date.new(2016, 9, 1),
                    :q20171 => Date.new(2017, 1, 1),
                    :q20172 => Date.new(2017, 3, 1),
                    :q20173 => Date.new(2017, 6, 1),
                    :q20174 => Date.new(2017, 9, 1),
                    :q20181 => Date.new(2018, 1, 1),
                    :q20182 => Date.new(2018, 3, 1),
                    :q20183 => Date.new(2018, 6, 1),
                    :q20184 => Date.new(2018, 9, 1)
                  }
    # We will overwrite this info on every import, in case one of these gets added by mistake.
    practice.surveys.where(survey_type: 'ABCS').delete_all
    abcs_fields.keys.each do |afld|
      if row[afld.to_s] == 1 then
        ds = abcs_fields[afld]
        srv = Survey.find_or_initialize_by(practice_id: practice.id, survey_type: "ABCS", date_sent: ds)
        srv.date_sent = ds
        srv.status = afld
        srv.save!
        result[:new_rows] += 1
      end
    end

  end

  def self.import_excel(file, spreadsheet_type)

    # raise spreadsheet_type
    result = Hash.new(0)

    result[:error_messages] = ""
    result[:spreadsheet_type] = "#{spreadsheet_type}"
    result[:original_filename] = file.original_filename

    spreadsheet = Roo::Spreadsheet.open(file)
    result[:file_info] = spreadsheet.info


    header = spreadsheet.row(1)
    if header.include?("PracticeID")
      (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        pid = row["PracticeID"].to_i
        if pid == 0
          result[:error_rows] += 1
          result[:error_messages] += "\nNo PracticeID value in row #{i}--data not usable."
        else
          prac = Practice.find_by(study_id: pid.to_s)
          if prac
            if spreadsheet_type == 'practice'
              survey_type = "Practice"
            elsif spreadsheet_type == 'staff_abcs'
              survey_type = "Staff"
            end

            # raise survey_type

            srv = Survey.find_or_initialize_by(practice_id: prac.id, survey_type: survey_type)

            # raise srv.survey_type

            already_existed = srv.persisted?

            if spreadsheet_type == 'staff_abcs'
              srv.date_sent = row["Sent"]
              srv.percent_complete = row["% of Staff completed"] || row["% of Staff completed "]
              srv.status = "complete" if srv.percent_complete == 1
              write_abcs(row, prac, result)
            elsif spreadsheet_type == 'practice' then
              srv.date_sent = row["Date sent"]
              srv.status = row["Status"]
            end

            if srv.save
              if already_existed
                result[:updated_rows] += 1
              else
                result[:new_rows] += 1
              end
            else
              result[:error_rows] += 1
              srv.errors.full_messages.each do |em|
                result[:error_messages] += "\n#{em}."
              end
            end
          else
            result[:error_rows] += 1
            result[:error_messages] += "\nNo practice found with PracticeID #{pid} (in row #{i})."
          end
        end
      end
    else
      result[:error_messages] = "Could not find a column headed 'PracticeID'.  Please correct your spreadsheet and try again."
    end

    return result
  end

  SURVEY_TYPES = {staff: "Staff",
                  prac: "Practice",
                  abcs: "ABCS"
  }

  SURVEY_STATUSES = {not_eligible: 'Not eligible',
                    not_sent: 'Not yet sent',
                    sent: 'Sent, no response yet',
                    completed: 'Completed',
                    declined: 'Declined'
  }

  SPREADSHEET_TYPES = {
    staff_abcs: 'Staff/ABCS',
    practice: 'Practice'
  }

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_partner!
  def index
    @page_title = "External Survey Management"
    @surveys = policy_scope(Survey).all
  end

  def practice_survey_practices
    # All practices who have returned the PAL but have not already 'completed' their practice survey.
    @practices = survey_needing_practices('Practice')
    render 'index'
  end

  def staff_survey_practices
    @practices = survey_needing_practices('Staff')
    render 'index'
  end

  def import
    if params[:file].nil?
      redirect_to surveys_path, alert: 'No file selected!'
    else
      @results = Survey.import_excel(params[:file], params[:spreadsheet_type])
    end
  end

private
  def survey_needing_practices(survey_type)
    allowed_sites = (policy_scope(Site).select(:id).map {|s| s.id}).join(', ')
    sql = "select s.status, p.*
          from  practices as p left join
                surveys as s
          on    p.id = s.practice_id        AND
                s.survey_type = '#{survey_type}'  AND
                s.status = 'complete'
          where p.site_id in (#{allowed_sites})   AND
                p.pal_status_cached = 'Returned'  AND
                s.practice_id IS NULL"
    return Practice.find_by_sql(sql)
  end

end

app/helpers/surveys_helper.rb
module SurveysHelper
  def surveyable_export(practices)
    require "csv"
    to_export = {
      site_id: 'Site',
      name: 'Practice Name',
      study_id: 'Practice ID',
      formatted_address: 'Address',
      pc_name: 'Primary Contact Name',
      pc_email1: 'Primary Contact E-Mail',
      welcome_date: 'FRIPC Date',
      ss_name: 'Staff Survey Recipient Name',
      ss_email: 'Staff Survey Recipient E-mail',
      drop_dt: 'Drop Date',
      c_name: 'Coach Name',
      c_email: 'Coach E-mail',
      pal_status_cached: 'PAL status',
      }
    csv_string = CSV.generate do |csv|
      csv << to_export.values
      practices.each do |p|
        pc = p.personnels.where(site_contact_primary: true).first
        fc = p.ivcontacts.where(contact_type: 1).order(:contact_dt).first
        pr = Partner.find(p.coach_id) if p.coach_id
        wanted_attributes = Hash.new
        to_export.keys.each do |k|
          wanted_attributes[k] = case k
          when :site_id
            p.site.name
          when :pc_name
            pc.name if pc
          when :pc_email1
            pc.email1 if pc
          when :welcome_date
            fc.contact_dt if fc
          when :ss_name
            fc.smsvy_name if fc
          when :ss_email
            fc.smsvy_email if fc
          when :c_name
            pr.name if pr
          when :c_email
            pr.email if pr
          else
            p.send(k)
          end # case
        end # keys.each
        csv << wanted_attributes.values
      end # practices.each
    end # csv.generate
  end
end

app/views/surveys/import.html.erb
<%= render 'layouts/header' %>
<div id = "wrapper">
  <table class = 'simple-grid'>
    <tr>
      <th>File uploaded:</th>
      <td><%= @results[:original_filename] %></td>
    </tr>
    <tr>
      <th>Spreadsheet type:</th>
      <td><%= @results[:spreadsheet_type] %></td>
    </tr>
    <tr>
      <th>New records created:</th>
      <td><%= @results[:new_rows] %></td>
    </tr>
    <tr>
      <th>Existing records updated:</th>
      <td><%= @results[:updated_rows] %></td>
    </tr>

    <tr>
      <th>Rows unable to process:</th>
      <td><%= @results[:error_rows] %></td>
    </tr>

    <tr>
      <th>Error Messages</th>
      <td><pre><%= @results[:error_messages] %></pre></td>
    </tr>

    <tr>
      <th>File Info:</th>
      <td><pre><%= @results[:file_info] %></pre></td>
    </tr>
  </table>
  <%= link_to 'Back', surveys_path %>
</div>

app/views/surveys/index.csv.erb
<%= raw(surveyable_export(@practices)) %>

app/views/surveys/index.html.erb
<%= render 'layouts/header' %>
<div id = "wrapper">
  <h1>Surveys</h1>
  <div>
    <h2>Download Spreadsheet of Practices Who Have Not Completed</h2>
    <ul>
      <li><%= link_to 'The first Practice Survey', practice_survey_practices_path(format: 'csv') %></li>
      <li><%= link_to 'The first Staff Survey', staff_survey_practices_path(format: 'csv') %></li>
    </ul>
  </div>

  <div style="border: 1px solid black ;">
    <h2>Upload Spreadsheet Of Survey Return Information</h2>
    <%= form_tag import_surveys_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= label_tag :spreadsheet_type, "Spreadsheet Type" %>
      <%= select_tag :spreadsheet_type, options_for_select(Survey::SPREADSHEET_TYPES.invert) %>
      <%= submit_tag "Upload", disabled: true %>
    <% end %>
  </div>

  <h2>Raw Survey Return Information</h2>
  <% if @surveys && @surveys.any? %>
    <table class='enable-data-table'>
      <thead>
        <tr>
          <th>Practice ID</th>
          <th>Site</th>
          <th>Name</th>
          <th>Survey Type</th>
          <th>Status</th>
          <th>Date Sent</th>
          <th>Percent Complete</th>
        </tr>
      </thead>
      <tbody>
        <% @surveys.each do |s| %>
          <tr>
            <td><%= s.practice.study_id %></td>
            <td><%= s.practice.site.name %></td>
            <td><%= s.practice.name %></td>
            <td><%= s.survey_type %></td>
            <td><%= s.status %></td>
            <td><%= s.date_sent %></td>
            <td style="text-align: right"><%= number_to_percentage(s.percent_complete * 100, precision: 0) if s.percent_complete %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h2>There are none!</h2>
  <% end %>
</div>